# Generated by Django 4.2.2 on 2023-06-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='cariation_category',
            new_name='variation_category',
        ),
    ]
