name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest  # Change to a Windows runner

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11.6]

    steps:
    - uses: actions/checkout@v2  # Updated to v2 since v3 is not available for Windows
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Updated to v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
